server:
  servlet:
    context-path: /api
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://111.229.106.212:3306/db_fox
    username: root
    password: Shuai3198@
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.octo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
