server:
  servlet:
    context-path: /api
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://111.229.106.212:3306/db_fox
    username: root
    password: Shuai3198@
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 111.229.106.212
    port: 6379
    password: Shuai3198@
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis-plus:
  type-aliases-package: com.octo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#file:
#  root:
#    directory: "C:\\Users\\zhang\\Desktop"
#  host: ""

file:
  root:
    directory: "/opt/upload"
  access:
    path: "http://octopi.site/file"



